# These are supported funding model platforms

github: [Ismail-2001]
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift plan name
# custom: # Replace with a custom link
