"""Add persistent RBAC tables and security audit log

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-15

The RBAC and security audit tables were defined in the ORM metadata
(ecommerce_ops.models.db) but were never created by a migration, so an
autogenerated alembic diff against a migration-built database would emit
CREATE TABLE for rbac_users / rbac_api_keys / security_audit_log. This
migration closes that gap and adds the audit_entries.action_id FK that was
omitted from 0001. Backfilled on 2026-08-15.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "rbac_users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False, server_default="viewer"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=False, server_default="0"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rbac_users_email", "rbac_users", ["email"], unique=True)
    op.create_index("ix_rbac_users_role", "rbac_users", ["role"])
    op.create_index("idx_rbac_users_role_active", "rbac_users", ["role", "is_active"])

    op.create_table(
        "rbac_api_keys",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("key_prefix", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["rbac_users.id"], name="rbac_api_keys_user_id_fkey"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rbac_api_keys_key_hash", "rbac_api_keys", ["key_hash"], unique=True)
    op.create_index("ix_rbac_api_keys_user_id", "rbac_api_keys", ["user_id"])

    op.create_table(
        "security_audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("user_email", sa.String(), nullable=True),
        sa.Column("api_key_id", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("risk_level", sa.String(), nullable=False, server_default="low"),
        sa.Column("timestamp", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["user_id"], ["rbac_users.id"], name="security_audit_log_user_id_fkey"),
        sa.ForeignKeyConstraint(
            ["api_key_id"], ["rbac_api_keys.id"], name="security_audit_log_api_key_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_security_audit_log_event_type", "security_audit_log", ["event_type"])
    op.create_index("ix_security_audit_log_action", "security_audit_log", ["action"])
    op.create_index("ix_security_audit_log_resource", "security_audit_log", ["resource"])
    op.create_index("ix_security_audit_log_user_id", "security_audit_log", ["user_id"])
    op.create_index("ix_security_audit_log_risk_level", "security_audit_log", ["risk_level"])
    op.create_index("ix_security_audit_log_timestamp", "security_audit_log", ["timestamp"])
    op.create_index(
        "idx_security_audit_type_time", "security_audit_log", ["event_type", "timestamp"]
    )
    op.create_index(
        "idx_security_audit_risk", "security_audit_log", ["risk_level", "timestamp"]
    )

    # Foreign key on audit_entries.action_id was present in ORM metadata but
    # omitted from 0001 — add it so a metadata diff against the DB is clean.
    op.create_foreign_key(
        "audit_entries_action_id_fkey",
        "audit_entries",
        "approval_actions",
        ["action_id"],
        ["id"],
    )


def downgrade() -> None:
    op.drop_constraint(
        "audit_entries_action_id_fkey", "audit_entries", type_="foreignkey"
    )
    op.drop_index("idx_security_audit_risk", table_name="security_audit_log")
    op.drop_index("idx_security_audit_type_time", table_name="security_audit_log")
    op.drop_index("ix_security_audit_log_timestamp", table_name="security_audit_log")
    op.drop_index("ix_security_audit_log_risk_level", table_name="security_audit_log")
    op.drop_index("ix_security_audit_log_user_id", table_name="security_audit_log")
    op.drop_index("ix_security_audit_log_resource", table_name="security_audit_log")
    op.drop_index("ix_security_audit_log_action", table_name="security_audit_log")
    op.drop_index("ix_security_audit_log_event_type", table_name="security_audit_log")
    op.drop_table("security_audit_log")
    op.drop_index("ix_rbac_api_keys_user_id", table_name="rbac_api_keys")
    op.drop_index("ix_rbac_api_keys_key_hash", table_name="rbac_api_keys")
    op.drop_table("rbac_api_keys")
    op.drop_index("idx_rbac_users_role_active", table_name="rbac_users")
    op.drop_index("ix_rbac_users_role", table_name="rbac_users")
    op.drop_index("ix_rbac_users_email", table_name="rbac_users")
    op.drop_table("rbac_users")
